/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#5f5e60",
        "inverse-primary": "#abc7ff",
        "inverse-surface": "#2f3034",
        "on-primary-container": "#fcfbff",
        "surface-variant": "#e3e2e7",
        "secondary-fixed": "#e4e2e4",
        "on-secondary-fixed-variant": "#474649",
        "inverse-on-surface": "#f1f0f5",
        "surface-bright": "#faf8fe",
        "tertiary-fixed-dim": "#c6c6c8",
        "primary-fixed": "#d7e2ff",
        "surface-container-high": "#e9e7ed",
        "on-secondary-container": "#636264",
        "on-background": "#1a1b1f",
        "surface-tint": "#005cbb",
        "surface": "#faf8fe",
        "primary-fixed-dim": "#abc7ff",
        "on-primary": "#ffffff",
        "primary-container": "#0071e3",
        "tertiary-container": "#727476",
        "secondary-fixed-dim": "#c8c6c8",
        "on-tertiary-fixed": "#1a1c1d",
        "error": "#ba1a1a",
        "surface-container-low": "#f4f3f8",
        "surface-dim": "#dad9df",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container": "#eeedf3",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c1c6d6",
        "on-tertiary-container": "#fbfbfd",
        "error-container": "#ffdad6",
        "on-surface-variant": "#414753",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1b1f",
        "tertiary-fixed": "#e2e2e4",
        "secondary-container": "#e2dfe1",
        "outline": "#717785",
        "on-primary-fixed-variant": "#00458f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#454749",
        "tertiary": "#5a5b5d",
        "primary": "#0059b5",
        "on-secondary-fixed": "#1b1b1d",
        "on-primary-fixed": "#001b3f",
        "surface-container-highest": "#e3e2e7",
        "background": "#faf8fe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "panel-width": "380px",
        gutter: "20px",
        "sidebar-width": "80px",
        "container-padding": "32px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "body-lg": ["17px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
